# Generated by Django 3.0.5 on 2020-05-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_best',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
